google/wire

_tutorial/README.md

Title says it all -- just a simple typo fix

Fix typo (missing "forgot") in comment

---

.travis.yml
internal/proxy/README.md
internal/proxy/makeproxy.sh

I have created `gs://wire-modules` to store the Wire dependencies. I ran the script in this commit to populate the contents of the GCS bucket and am updating Travis to point to the new proxy.
Fixes #81

internal/proxy: port script from Go Cloud to create module proxy

---

internal/wire/testdata/PkgImport/foo/wire.go

This got removed as part of my gofmt run on #101.
/cc @doodlesbykumbi

internal/wire/testdata/PkgImport: add back duplicate import

---

internal/wire/analyze.go
internal/wire/parse.go

Avoids having parallel arrays for conceptually related data.

internal/wire: move field name into ProviderInput

---

.travis.yml

I'm not sure why the previous approach of `git checkout -- .` stopped working, but it did :-|. The tests fail with extra `\r` characters in the golden files.
I tried a variety of `git config` commands, nothing worked. I found this solution here: https://travis-ci.community/t/files-in-checkout-have-eol-changed-from-lf-to-crlf/349/2.
Fixes #119.

travis: re-enable windows build

---

internal/alldeps
internal/listdeps.sh
internal/runtests.sh

Dependency checking for CI - ensures a PR doesn't modify our
dependencies without anyone noticing.
Similar to https://github.com/google/go-cloud/pull/1284

all: add dependency checking to the script Travis runs

---

.codecov.yml

I think this should prevent `codecov` from blocking commits like it is in #1355 (because of the target=0).

travis: add codecov.yml with threshold=0

---

docs/guide.md

Add a provider that takes in a `Fooer` so that it becomes more clear.
Updates #116

guide: clarify interface binding examples

---

docs/best-practices.md
docs/guide.md

Fixes #151 : add the usage of `wire.Struct` to guide and change the old syntax.
Fixes #120 : change the old syntax and update the guide about the new `wire.Bind` usage.
Fixes #116 : remove the second example as the example appears to be an edge-case and we should consider adding it back when we have some real world example.

docs: update docs with the bind and struct changes

---

wire.go

Fixes #166.
The user interpreted "parameters" here to mean the parameters to `NewSet`, when it means the parameters to the function being passed to `NewSet`.

docs: clarify docstring about function parameters being of non-identical types

---

cmd/wire/main.go
go.mod
go.sum
internal/alldeps

Fixes #62.
Sample output:
```
$ wire help
Usage: wire <flags> <subcommand> <subcommand args>
Subcommands:
check            prints any Wire errors found
diff             outputs a diff between the existing wire_gen.go files and what gen would generate
gen              generates the wire_gen.go file for each package
help             describe subcommands and their syntax
show             describes all top-level provider sets
Use "wire flags" for a list of top-level flags
$ wire commands
commands
flags
help
check
diff
gen
show
$ wire flags
$ wire help
Usage: wire <flags> <subcommand> <subcommand args>
Subcommands:
check            prints any Wire errors found
commands         list all command names
diff             outputs a diff between existing wire_gen.go files and what gen would generate …
```

wire: use subcommands package, improving help

---

internal/wire/analyze.go
internal/wire/parse.go
internal/wire/testdata/StructWithPreventTag/foo/foo.go
internal/wire/testdata/StructWithPreventTag/foo/wire.go
internal/wire/testdata/StructWithPreventTag/pkg
internal/wire/testdata/StructWithPreventTag/want/wire_errs.txt
internal/wire/testdata/UnusedProviders/foo/foo.go
internal/wire/testdata/UnusedProviders/foo/wire.go
internal/wire/testdata/UnusedProviders/want/wire_errs.txt

Updates #110 
1. When using "*", wire will omit the fields with "-" tag.
1. When specifying a prevented field, wire will give an error.

wire: support using '-' tag to prevent filling struct fields

---

internal/wire/wire.go

Simplifying the code by replacing the `reservedKeyword` map with standard `token` api.

internal/wire: replace keyword list with token api

---

docs/guide.md
internal/wire/analyze.go
internal/wire/parse.go
internal/wire/testdata/FieldsOfStruct/foo/foo.go
internal/wire/testdata/FieldsOfStruct/foo/wire.go
internal/wire/testdata/FieldsOfStruct/want/program_out.txt
internal/wire/testdata/FieldsOfStruct/want/wire_gen.go
internal/wire/wire.go
wire.go

wire: FieldsOf now provides a pointer to the field type as well as the actual field type

---

.travis.yml
go.mod

all: enable go 1.13

---

docs/guide.md
internal/wire/analyze.go
internal/wire/parse.go
internal/wire/testdata/FieldsOfStruct/foo/wire.go
internal/wire/testdata/FieldsOfStruct/want/program_out.txt
internal/wire/testdata/FieldsOfStruct/want/wire_gen.go
internal/wire/testdata/FieldsOfStructDoNotProvidePtrToField/foo/foo.go
internal/wire/testdata/FieldsOfStructDoNotProvidePtrToField/foo/wire.go
internal/wire/testdata/FieldsOfStructDoNotProvidePtrToField/pkg
internal/wire/testdata/FieldsOfStructDoNotProvidePtrToField/want/wire_errs.txt
internal/wire/testdata/FieldsOfStructPointer/foo/foo.go
internal/wire/testdata/FieldsOfStructPointer/foo/wire.go
internal/wire/testdata/FieldsOfStructPointer/want/program_out.txt
internal/wire/testdata/FieldsOfStructPointer/want/wire_gen.go
wire.go

@zombiezen pointed out (hah!) that `FieldsOf` should not provide a pointer to field types in cases where the struct itself is not a pointer; the struct is then a temporary variable.
I moved the previously-working "pointer to field type" test from `FieldsOfStruct` to `FieldsOfStructPointer`, and added a new non-working testcase attempting to provide a ptr-to-field from a non-pointer struct (expected to fail).
Fixes #208.

wire: wire.FieldsOf should not provide pointer to field type for non-pointer structs

---

cmd/wire/main.go
internal/wire/wire.go

cmd: Allowing to change the output file name from wire_gen.go to other

---

.travis.yml
internal/wire/wire_test.go

Upstream Go issue has been fixed in Go 1.13. I removed older versions of Go from the Travis build matrix.
Fixes #66

internal/wire: mark tests as parallelizable

---

internal/wire/parse.go
internal/wire/testdata/StructNotAStruct/foo/foo.go
internal/wire/testdata/StructNotAStruct/foo/wire.go
internal/wire/testdata/StructNotAStruct/pkg
internal/wire/testdata/StructNotAStruct/want/wire_errs.txt

internal/wire: fix crash when giving wire.Struct a bad first argument

---

go.sum
internal/wire/parse.go

PR fixes the panic that I've seen with some "edge case" configurations due to using a `nil` object in a compound "chain" of functions calls (unfortunately, didn't save a reproducible sample).

internal/wire: fix panic in objectCache.processExpr

---

docs/guide.md

should be "return foobarbaz.Baz{}, err"

update guide.md Code generated by Wire

---

README.md

go get p has been replaced by go install p@latest.
Fixes #338.

README: fix install instructions

---

_tutorial/README.md

Fixes #338 on `_tutorial/README.md`

README: fix install instructions on tutorial
